Repository eslint/eslintrc, pull requests merged in 2020-09, with the labels that each got.

#5 Fix: add missing dependencies
  .eslintrc.js
  .npmrc
  conf/environments.js
  conf/eslint-all.js
  lib/cascading-config-array-factory.js
  lib/config-array-factory.js
  lib/index.js
  lib/shared/config-validator.js
  package-lock.json
  package.json
Labels: bug, triage

#8 Fix: Release version number
  package.json
Labels: accepted, bug

#10 Chore: use GitHub Actions
  .github/workflows/ci.yml
  package.json
Labels: triage
