Repository eslint/eslintrc, pull requests merged in 2021-07, with the labels that each got.

#44 fix failing test
  tests/lib/config-array-factory.js
Labels: triage

#45 Chore: pin fs-teardown@0.1.1
  package.json
Labels: chore

#42 Fix: ensure config files are files
  lib/config-array-factory.js
  tests/lib/config-array-factory.js
Labels: accepted, bug
