Repository eslint/eslintrc, pull requests merged in 2021-08, with the labels that each got.

#39 Breaking: Switch to ESM (fixes #35)
  .editorconfig
  .eslintignore
  .eslintrc.cjs
  .github/workflows/ci.yml
  conf/config-schema.js
  conf/environments.js
  conf/eslint-all.cjs
  conf/eslint-recommended.cjs
  lib/cascading-config-array-factory.js
  lib/config-array-factory.js
  lib/config-array/config-array.js
  lib/config-array/config-dependency.js
  lib/config-array/extracted-config.js
  lib/config-array/ignore-pattern.js
  lib/config-array/index.js
  lib/config-array/override-tester.js
  lib/flat-compat.js
  lib/index.js
  lib/shared/ajv.js
  lib/shared/config-ops.js
  lib/shared/config-validator.js
  lib/shared/deprecation-warnings.js
  lib/shared/naming.js
  lib/shared/relative-module-resolver.js
  lib/shared/types.js
  package.json
  rollup.config.js
  tests/_utils/index.js
  tests/fixtures/config-file/extends-chain-2/parser.cjs
  tests/fixtures/config-file/js/.eslintrc.broken.cjs
  tests/fixtures/config-file/js/.eslintrc.cjs
  tests/fixtures/config-file/js/.eslintrc.parser.cjs
  tests/fixtures/config-file/js/.eslintrc.parser2.cjs
  tests/fixtures/config-file/js/.eslintrc.parser3.cjs
  tests/fixtures/config-hierarchy/fileexts/.eslintrc.cjs
  tests/fixtures/config-hierarchy/plugins/node_modules/eslint-plugin-example-with-rules-config.js
  tests/fixtures/config-rule/schemas.cjs
  tests/fixtures/configurations/parser/.eslintrc.json
  tests/fixtures/configurations/parser/custom.cjs
  tests/fixtures/eslint-all.cjs
  tests/fixtures/eslint-recommended.cjs
  tests/fixtures/rules/.jshintignore
  tests/fixtures/rules/custom-rule.cjs
  tests/fixtures/rules/dir1/no-strings.cjs
  tests/fixtures/rules/dir2/no-literals.cjs
  tests/fixtures/rules/fix-types-test/no-program.cjs
  tests/fixtures/rules/make-syntax-error-rule.cjs
  tests/fixtures/rules/wrong/custom-rule.cjs
  tests/lib/cascading-config-array-factory.js
  tests/lib/commonjs.cjs
  tests/lib/config-array-factory.js
  tests/lib/config-array/config-array.js
  tests/lib/config-array/config-dependency.js
  tests/lib/config-array/extracted-config.js
  tests/lib/config-array/ignore-pattern.js
  tests/lib/config-array/override-tester.js
  tests/lib/flat-compat.js
  tests/lib/shared/config-ops.js
  tests/lib/shared/naming.js
  tests/lib/shared/relative-module-resolver.js
Labels: triage

#47 Chore: use actions/setup-node@v2
  .github/workflows/ci.yml
Labels: triage

#46 Update: Export environments
  lib/index.js
  tests/lib/commonjs.cjs
Labels: enhancement, accepted

#49 Upgrade: Espree (fixes #41)
  package.json
Labels: accepted, chore

#52 Upgrade: debug@4.3.2
  package.json
Labels: accepted

#51 Update: Add /universal entrypoint (fixes #50)
  lib/index-universal.js
  lib/shared/ajv.js
  package.json
  rollup.config.js
  tests/lib/commonjs.cjs
Labels: enhancement
