Repository eslint/eslintrc, pull requests merged in 2022-04, with the labels that each got.

#78 build: add node v18
  .github/workflows/ci.yml
Labels: accepted, build

#77 fix: use custom Rollup plugin for `import.meta.url`
  .gitignore
  package.json
  rollup.config.js
  tests/lib/commonjs.cjs
Labels: bug

#79 chore: update license copyright holder
  LICENSE
Labels: triage, chore
